# This file was generated by GoReleaser. DO NOT EDIT.
class EcsRunner < Formula
  desc "ecs-runner allows you to run ECS tasks"
  homepage "https://github.com/ministryofjustice/opg-ecs-helper"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ministryofjustice/opg-ecs-helper/releases/download/v0.1.1/opg-ecs-helper_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "bb6304e23bcf2e88ba577ee902a3aefa29ae67008728d21876f012b45b7665e3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ministryofjustice/opg-ecs-helper/releases/download/v0.1.1/opg-ecs-helper_0.1.1_Linux_x86_64.tar.gz"
      sha256 "02a4f86976bb64e5901f86985628e6bc7b482d9449a664c0476b7fa7732e9f7a"
    end
  end

  def install
    bin.install "ecs-runner"
  end
end
