# This file was generated by GoReleaser. DO NOT EDIT.
class OpgRunner < Formula
  desc "ecs-runner allows you to run ECS tasks"
  homepage "https://github.com/ministryofjustice/opg-ecs-helper"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ministryofjustice/opg-ecs-helper/releases/download/v0.1.1/opg-ecs-helper_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "ad2f1e6a3e85872aaadecaefca3ac5801f28c7673b8b0ff54d9bee1225ac6373"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ministryofjustice/opg-ecs-helper/releases/download/v0.1.1/opg-ecs-helper_0.1.1_Linux_x86_64.tar.gz"
      sha256 "4e991639eaeac7107fb44f44f8b3e2e9af2e7763fc13920951c3e1e4183e3bb5"
    end
  end

  def install
    bin.install "ecs-runner"
  end
end
